### ISSUE TITLE
Missing reference can result in runtime error

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#120]
If you ever have a reference, like to a response definition, and that reference does not point to a valid response, when attempting to validate that response you can get a runtime error do to the `schema` for the response being `undefined`.

**Comment by whitlockjc** [comment]
Here is an example invocation:

```
swagger-tools validate config/swagger.yaml

API Errors:

  #/paths/~1users~1{id}/post/responses/200/$ref: Response could not be resolved: #/responsed/singleUser

TypeError: Cannot call method 'map' of undefined
    at toJsonPointer (/Users/not-you/workspaces/personal/swagger-tools/lib/helpers.js:149:22)
    at /Users/not-you/workspaces/personal/swagger-tools/lib/helpers.js:166:55
    at Function.forEach (/Users/not-you/workspaces/personal/swagger-tools/node_modules/lodash/dist/lodash.js:3297:15)
    at printErrorsOrWarnings (/Users/not-you/workspaces/personal/swagger-tools/lib/helpers.js:165:7)
    at Object.printValidationResults (/Users/not-you/workspaces/personal/swagger-tools/lib/helpers.js:185:5)
    at /Users/not-you/workspaces/personal/swagger-tools/bin/swagger-tools:227:28
    at cbWrapper (/Users/not-you/workspaces/personal/swagger-tools/lib/specs.js:941:5)
    at validateSwagger2_0 (/Users/not-you/workspaces/personal/swagger-tools/lib/specs.js:936:3)
    at validateSemantically (/Users/not-you/workspaces/personal/swagger-tools/lib/specs.js:946:5)
    at Specification.<anonymous> (/Users/not-you/workspaces/personal/swagger-tools/lib/specs.js:1145:7)
```
