### ISSUE TITLE
Lack of request parameter name in validation message

### ISSUE THREAD

**Issue by w2iktor** [apigee-127/swagger-tools#175]
I'm trying to sent  request without location parameter to weather sample application.
Instead of receiving message like 'Location parameter is required' I've got 'Error: Is required'.

It seems like there is some bug with validationMessage in swagger-validator.js

Full stackTrace:
```
Error: Is required
    at throwErrorWithCode (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/lib/validators.js:97:13)
    at Object.validateRequiredness (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/lib/validators.js:405:5)
    at /home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/middleware/swagger-validator.js:285:32
    at /home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:249:17
    at /home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:46:24)
    at async.each (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:248:13)
    at Object.map (/home/wiktor/workspace/examples/swagger-tools/examples/2.0/node_modules/swagger-tools/node_modules/async/lib/async.js:219:23)
```

**Comment by whitlockjc** [comment]
Whenever we validate requests, we have to intercept the error message and augment the error message to include the parameter name in the message.  All of our tests test the error object but what you're seeing is the error stack, typically outputted by the default error handler middleware, and its _message_ didn't get augmented to match the error message.  This has been fixed but just know that if you were to use the error object yourself in an error handler, its message was fine.
