### ISSUE TITLE
better error message for unexpected response type

### ISSUE THREAD

**Issue by reesew** [apigee-127/swagger-tools#232]
When validating responses, if a response code is returned which doesn't match one in the spec, and `default` isn't defined, the resulting error is confusing: 

```
Stack: TypeError: Cannot read property 'type' of undefined
    at Object.isModelParameter (/var/www/node_modules/swagger-tools/middleware/helpers.js:55:14)
    at validateValue (/var/www/node_modules/swagger-tools/middleware/swagger-validator.js:91:26)
    at ServerResponse.end (/var/www/node_modules/swagger-tools/middleware/swagger-validator.js:210:7)
    at ServerResponse.send (/var/www/node_modules/express/lib/response.js:195:10)
    at ServerResponse.json (/var/www/node_modules/express/lib/response.js:240:15)
```

For example, when only a 200 response is defined for 'PUT /pets', when the validator encounters a 201 response, it should say something about no `201` or `default` response being defined in the swagger object/swagger.json

**Comment by whitlockjc** [comment]
Can you give me an example, both of the Swagger document and the code used for the server?

**Comment by reesew** [comment]
The following produces the described problem, but works correctly when `res.status(201);` is removed

swagger.json
```json
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Pet API"
    },
    "paths": {
        "/pet": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pet"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pet": {
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        }
    }
}
```

index.js
```javascript
var express = require("express");
var swaggerTools = require('swagger-tools');
var app = express();

var spec = require('./swagger.json');

// Validate request and response using swagger spec
swaggerTools.initializeMiddleware(spec, function onInitializeSwaggerMiddleware(middleware) {
    app.use(middleware.swaggerMetadata());

    app.use(middleware.swaggerValidator({
        validateResponse: true
    }));
});

app.get("/pet", function onGetPet(req, res, next) {
    res.status(201);
    res.json([ { 'id': 1 } ]);
});

app.listen(80, function onServerStart() {
    console.log("Starting server on port 80");
});
```

**Comment by nikdunn** [comment]
+1 This issue got me today.

**Comment by whitlockjc** [comment]
So basically if there is no `default` response and we cannot find the proper response based on the HTTP verb, just say so in an error instead of assuming we found one?

**Comment by nikdunn** [comment]
That would be perfect.
