### ISSUE TITLE
Pass parameters to bodyParser

### ISSUE THREAD

**Issue by amirbaer** [apigee-127/swagger-tools#248]
Hi all,

I am sending large (> 100kb) requests to the swagger service and receiving the following error:

```
error: rest_api.js:86:16 - [2015-07-16 17:59:17] execution.services.restApi: pre-route middleware error ERROR={"expected":137437,"length":137437,"limit":102400,"status":413,"statusCode":413,"message":"requ
est entity too large","type":"entity.too.large"}, ERROR_MSG=request entity too large, ERROR_STACK=Error: request entity too large
    at readStream (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:179:15)
    at getRawBody (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/node_modules/body-parser/node_modules/raw-body/index.js:97:12)
    at read (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/node_modules/body-parser/lib/read.js:68:3)
    at jsonParser (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/node_modules/body-parser/lib/types/json.js:121:5)
    at /home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/middleware/swagger-metadata.js:61:9
    at urlencodedParser (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/node_modules/body-parser/lib/types/urlencoded.js:95:37)
    at bodyParser (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/middleware/swagger-metadata.js:57:5)
    at /home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/middleware/swagger-metadata.js:201:5
    at /home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:246:17
    at /home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:122:13
    at _each (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:46:13)
    at async.each (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:245:13)
    at Object.map (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/async/lib/async.js:216:23)
    at processOperationParameters (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/middleware/swagger-metadata.js:171:9)
    at swaggerMetadata (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/swagger-tools/middleware/swagger-metadata.js:456:14)
    at call (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/connect/lib/proto.js:210:7)
    at next (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/connect/lib/proto.js:154:5)
    at Function.app.handle (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/connect/lib/proto.js:157:3)
    at Server.app (/home/amirbaer/workspace/safebreach/bitbucket/execution/node_modules/connect/lib/connect.js:28:37)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
```

As far as I can tell the problem has to do with the issue described here:
http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large

It can be solved by passing bodyParser's json constructor an options object with a larger limit.
This constructor is called in file "middleware/swagger-metadata.js", line 45 (version 0.8.7):
```var jsonBodyParser = bp.json();```
and if I change it to:
```var jsonBodyParser = bp.json({limit: 1000000});```
my problem is solved.

However, I couldn't find any way to pass this parameter to bodyParser through swagger.
Is there a way?

Thanks in advance,
Amir Baer

**Comment by whitlockjc** [comment]
If you need to configure your body-parser, just provide it yourself.  The parsers included with swagger-tools are just fallbacks and if you provide your own, the swagger-tools parsers will not be used.  So to fix this, just register your specially configured body-parser before you initialize the swagger-tools middleware and everything should just work.

**Comment by amirbaer** [comment]
@whitlockjc Thanks for the super-quick response.
I did not know this was an option, I just checked it:
```
bodyParser = require('body-parser');
app.use(bodyParser.json({ limit: 1000000 }));
```
It worked as you said - thank you!

**Comment by whitlockjc** [comment]
The middleware documentation mentions this but it wouldn't hurt to throw a working example in there.  I'll get on it.

**Comment by vomc** [comment]
@whitlockjc quick question: does using the standard express `bodyParser` as shown above mean that swagger will no longer validate the request/response body?
