### ISSUE TITLE
App fails on the response validation

### ISSUE THREAD

**Issue by wingedfox** [apigee-127/swagger-tools#388]
Hi,

When I trying to enable response validation and validation fails, I could not catch the error.

1st fail because of z-schema's broken rendering of json with circular references

Param
```
[ { pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$',
    type: 'string',
    '$schema': 'http://json-schema.org/draft-04/schema#',
    '__$schemaResolved': 
     { default: {},
       dependencies: [Object],
       properties: [Object],
       type: 'object',
       definitions: [Object],
       description: 'Core schema meta-schema',
       '$schema': 'http://json-schema.org/draft-04/schema#',
       id: 'http://json-schema.org/draft-04/schema#',
       '__$schemaResolved': [Circular],
       '__$compiled': true,
       '__$validated': true } } ]
```
Stack
```
[2016-05-30 12:47:07.988] [ERROR] default - [TypeError: Converting circular structure to JSON]
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Report.addCustomError (/opt/app/node_modules/z-schema/src/Report.js:166:71)
    at Report.addError (/opt/app/node_modules/z-schema/src/Report.js:150:10)
    at ZSchema.JsonValidators.enum (/opt/app/node_modules/z-schema/src/JsonValidation.js:257:20)
    at ZSchema.exports.validate (/opt/app/node_modules/z-schema/src/JsonValidation.js:516:39)
    at ZSchema.JsonValidators.anyOf (/opt/app/node_modules/z-schema/src/JsonValidation.js:285:39)
    at ZSchema.exports.validate (/opt/app/node_modules/z-schema/src/JsonValidation.js:516:39)
    at ZSchema.recurseObject (/opt/app/node_modules/z-schema/src/JsonValidation.js:440:30)
    at ZSchema.exports.validate (/opt/app/node_modules/z-schema/src/JsonValidation.js:525:27)
    at ZSchema.recurseObject (/opt/app/node_modules/z-schema/src/JsonValidation.js:440:30)
```

2nd fail with commented out z-schema's stringify problem:
```
[2016-05-30 12:38:01.457] [ERROR] default - { [Error: Response validation failed: failed schema validation]
  code: 'SCHEMA_VALIDATION_FAILED',
  failedValidation: true,
  results: 
   { errors: [ [Object], [Object], [Object], [Object] ],
     warnings: [] },
  originalResponse: <Buffer 7b 7d> }
Error: Response validation failed: failed schema validation
    at throwErrorWithCode (/opt/app/node_modules/swagger-tools/lib/validators.js:121:13)
    at Object.module.exports.validateAgainstSchema (/opt/app/node_modules/swagger-tools/lib/validators.js:176:7)
    at /opt/app/node_modules/swagger-tools/middleware/swagger-validator.js:143:22
    at /opt/app/node_modules/swagger-tools/node_modules/async/lib/async.js:356:13
/opt/app/node_modules/swagger-tools/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/opt/app/node_modules/swagger-tools/node_modules/async/lib/async.js:355:9)
    at Object.map (/opt/app/node_modules/swagger-tools/node_modules/async/lib/async.js:337:20)
    at validateValue (/opt/app/node_modules/swagger-tools/middleware/swagger-validator.js:136:11)
    at ServerResponse.res.end (/opt/app/node_modules/swagger-tools/middleware/swagger-validator.js:254:9)
    at ServerResponse.send (/opt/app/node_modules/express/lib/response.js:204:10)
```

**Comment by whitlockjc** [comment]
All errors are sent downstream via `next` so to catch them, just register an error handler middleware.

**Comment by wingedfox** [comment]
Unfortunately, they are not caught and are not passed to next.

REQUEST validation works well, but RESPONSE does not.

**Comment by whitlockjc** [comment]
I think you're right.  We do send errors downstream via `next` but only errors we trap, not the validation error itself.  _(See: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-validator.js#L34)_  The reason we do this is because if we don't, we can end up in an infinite loop.  Let me give this some thought.
