### ISSUE TITLE
'TypeError: JsonRefs.pathToPtr is not a function' on certain import swagger.json

### ISSUE THREAD

**Issue by qyanu** [apigee-127/swagger-tools#410]
Hello,

Considering that the CLI call
`./bin/swagger-tools validate swagger.json`
will have to deal with arbitrary user input, any malformed input swagger.json should result in an appropriate error message.

the following invalid swagger.json:
```
$ cat swagger.json
{
    "swagger":"2.0"
}
```

if not properly validated before processing, and thus results in:
```
$ ./swagger-tools/bin/swagger-tools validate swagger.json

API Errors:

/home/max-julian/work/projects/oeamtc/swagger-tools/lib/helpers.js:201
      stream(new Array(indent + 1).join(' ') + JsonRefs.pathToPtr(entry.path) + ': ' + entry.message);
                                                        ^

TypeError: JsonRefs.pathToPtr is not a function
    at /home/max-julian/work/projects/oeamtc/swagger-tools/lib/helpers.js:201:57
    at arrayEach (/home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/lodash-compat/internal/arrayEach.js:15:9)
    at Object.each (/home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/lodash-compat/internal/createForEach.js:15:9)
    at printErrorsOrWarnings (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/helpers.js:200:7)
    at Object.module.exports.printValidationResults (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/helpers.js:220:5)
    at /home/max-julian/work/projects/oeamtc/swagger-tools/bin/swagger-tools:312:19
    at /home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:1231:7
    at /home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:1073:29
    at validateAgainstSchema (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:712:14)
    at validateStructurally (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:1045:3)
```

the swagger-tools version executed above was obtained via 'git clone' from this github repository and is the most resent commit on master:
```
$ git status; git show --format=format:%H HEAD
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
b077f641343ffa1a12d4970c24283f9249990154
```

The desired output of `./bin/swagger-tools validate swagger.json` would be the report, that the provided swagger.json is not a valid swagger 2.0 specification
  a) required `info` is missing
  b) required `path` is missing

**Comment by whitlockjc** [comment]
I'll give it a peek.
