### ISSUE TITLE
'Error: done must be a function' on certain swagger.json

### ISSUE THREAD

**Issue by qyanu** [apigee-127/swagger-tools#411]
Hello,

the following valid swagger.json produces the abovementioned error message, although the example swagger.json is valid according to http://swagger.io/specification/ (albeit empty).

```
$ cat swagger.json 
{
    "swagger":"2.0",
    "info":{
        "version": "p-AliceBlue",
        "title":"Test Swagger Json"
    },
    "paths":{

    }
}
```

```
$ ./swagger-tools/bin/swagger-tools validate swagger.json 
/home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/json-refs/index.js:323
    throw new Error('done must be a function');
    ^

Error: done must be a function
    at Object.resolveRefs (/home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/json-refs/index.js:323:11)
    at resolveRefs (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:680:14)
    at validateAgainstSchema (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:718:3)
    at validateStructurally (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:1045:3)
    at Specification.validate (/home/max-julian/work/projects/oeamtc/swagger-tools/lib/specs.js:1229:3)
    at /home/max-julian/work/projects/oeamtc/swagger-tools/bin/swagger-tools:328:21
    at /home/max-julian/work/projects/oeamtc/swagger-tools/bin/swagger-tools:118:5
    at /home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/async/lib/async.js:52:16
    at /home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/async/lib/async.js:361:13
    at /home/max-julian/work/projects/oeamtc/swagger-tools/node_modules/async/lib/async.js:52:16
```

the swagger-tools version in use was optained via `git clone` from this github repository, and is at the following version/commit:
```
$ ( cd swagger-tools/; git status; git show --format=format:%H HEAD )
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
b077f641343ffa1a12d4970c24283f9249990154
```

**Comment by qyanu** [comment]
this bug does occur when tag v0.9.12 is checked out, but does not occur when tag v0.9.11 is checked out.

**Comment by whitlockjc** [comment]
I'll give it a peek.
