### ISSUE TITLE
Getting Range error 0 when trying to validate the api request based on swagger definitions

### ISSUE THREAD

**Issue by Sheoshobhit** [apigee-127/swagger-tools#457]
hi,
I am trying to use the swagger-tools for schema validations on my apis, when checking for the validations i am getting an error as shown below. I am trying to send a invalid schema in the request and hoping to get a error message for invalid schema, but i get below error , i am using express for the server

RangeError: Invalid status code: 0
<br> &nbsp; &nbsp;at ServerResponse.writeHead (_http_server.js:192:11)
<br> &nbsp; &nbsp;at ServerResponse.writeHead (D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\on-headers\index.js:55:19)
<br> &nbsp; &nbsp;at ServerResponse._implicitHeader (_http_server.js:157:8)
<br> &nbsp; &nbsp;at ServerResponse.OutgoingMessage.end (_http_outgoing.js:571:10)
<br> &nbsp; &nbsp;at ServerResponse.send (D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\express\lib\response.js:205:10)
<br> &nbsp; &nbsp;at ServerResponse.json (D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\express\lib\response.js:250:15)
<br> &nbsp; &nbsp;at handler (D:\CDE-SOURCE_NEW\CDE-Proxy\dist\server.js:2611:31)
<br> &nbsp; &nbsp;at Layer.handle_error (D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\express\lib\router\layer.js:71:5)
<br> &nbsp; &nbsp;at trim_prefix (D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\express\lib\router\index.js:310:13)
<br> &nbsp; &nbsp;at D:\CDE-SOURCE_NEW\CDE-Proxy\node_modules\express\lib\router\index.js:280:7

**Comment by whitlockjc** [comment]
I don't see `swagger-tools` in the stacktrace at all.  I would figure if `swagger-tools` were at fault, or involved, I'd see its mention in the stacktrace.  Do you have another stacktrace that is more complete, showing `swagger-tools`' involvement?
