### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by shraddha18** [apigee-127/swagger-tools#525]
I am trying to send a post request `localhost:5000/v2/user/shipping` which lets me store data to a local mySQL database using Node.js and Express.js. However inspite of providing the body parameters via postman I get the following error:
```shell
swagger-tools:middleware:metadata POST /v2/user/shipping +18s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +0ms
  swagger-tools:middleware:metadata   Processing Parameters +1ms
  swagger-tools:middleware:metadata     body +21ms
  swagger-tools:middleware:metadata       Type: object +0ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
util.js:108
          str += String(arguments[a++]);
                 ^

TypeError: Cannot convert object to primitive value
    at String (<anonymous>)
    at Object.exports.format (util.js:108:18)
    at Function.log (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/debug/src/node.js:127:35)
    at debug (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/debug/src/debug.js:114:11)
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-metadata.js:212:7
    at arrayEach (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/lodash-compat/index.js:1421:13)
    at Function.<anonymous> (/Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/lodash-compat/index.js:3482:13)
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/swagger-tools/middleware/swagger-metadata.js:199:7
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:52:16
    at /Users/shraddharavishankar/Documents/FLATLAY/Downloads/nodejs-server-server_V2_copy/node_modules/async/lib/async.js:361:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flatlay@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flatlay@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Is this some middleware issue? or is it something to do with node?

The javascript snippet for the same is
```javascript
exports.userShipping = function(args, res, next) {
  /**
   * Add shipping
   * Detail information for shipping
   *
   * body Shipping Created user object
   * no response value expected for this operation
   **/
	 var response = [];
	 if(
		 typeof args.body.trackingId !== 'undefined' &&
		 typeof args.body.title !== 'undefined' &&
		 typeof args.body.firstName !== 'undefined' &&
		 typeof args.body.lastName !== 'undefined' &&
		 typeof args.body.apartmentNumber !== 'undefined' &&
		 typeof args.body.streetAddress !== 'undefined' &&
		 typeof args.body.city !== 'undefined' &&
		 typeof args.body.state !== 'undefined' &&
		 typeof args.body.zip !== 'undefined' &&
		 typeof args.body.country !== 'undefined' &&
		 typeof args.body.shippingDate !== 'undefined' &&
		 typeof args.body.estimatedArrival !== 'undefined' &&
		 typeof args.body.carrier !== 'undefined' &&
		 typeof args.body.requestAddress !== 'undefined'

 	 ){
		 var trackingId = args.body.trackingId,
		 		 title = args.body.title,
				 firstName = args.body.firstName,
				 lastName = args.body.lastName,
				 apartmentNumber = args.body.apartmentNumber,
				 streetAddress = args.body.streetAddress,
				 city = args.body.city,
				 state = args.body.state,
				 zip = args.body.zip,
				 country = args.body.country,
				 shippingDate = moment(Date.now()).format('YYYY-MM-DD HH:mm:ss'),
				 estimatedArrival = moment(Date.now()).format('YYYY-MM-DD HH:mm:ss'),
				 carrrier = args.body.carrier,
				 requestAddress = args.body.requestAddress;
			connection.query('INSERT INTO shipping (trackingId, title, firstName, lastName, apartmentNumber, streetAddress, city, state, \
			zip, country, shippingDate, estimatedArrival, carrrier, requestAddress)\
			VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
			[trackingId, title, firstName, lastName, apartmentNumber, streetAddress, city, state, zip, country, shippingDate, estimatedArrival, carrrier, requestAddress],
			function(err,result){
				if(!err){
					if(result.affectedRows != 0){
						response.push({'result' : 'success'});
					}else{
						response.push({'msg' : 'No Result Found'});
					}
					res.setHeader('Content-Type', 'application/json');
			    res.status(200).send(JSON.stringify(response));
				}else{
					res.status(400).send(err);
				}
			});
	 }
	 else{
		 response.push({'result' : 'error', 'msg' : 'Please fill required details'});
		 res.setHeader('Content-Type', 'application/json');
     res.status(200).send(JSON.stringify(response));
	 }
   console.log('Hola User to shipping');
   res.end();
}
```
It was working fine until a day ago. I ran a react file today in a separate folder and it just stopped working after that. I am not sure if its because of the same. Help! 😢

**Comment by whitlockjc** [comment]
The error mentioned in the stack trace is not from `swagger-tools`:

```
util.js:108
          str += String(arguments[a++]);
```

But, what I can gather from this is it looks when you write your record to the database, there is one column expecting a `String` and you're giving it an `Object`.  This doesn't seem to be related to `swagger-tools` so I'm going to close the issue.  You can re-open it if you disagree.  Regardless, I will continue to help you if at all possible.
