### ISSUE TITLE
Optional date not included in params causes crash

### ISSUE THREAD

**Issue by blakebyrnes** [apigee-127/swagger-tools#541]
If you have a date setup as an optional param, there's a crash in 0.10.3.  Appears to just be missing a check that the date is not null or undefined.

TypeError: Cannot read property 'toString' of null
  at Object.module.exports.isValidDate (/Users/blakebyrnes/Projects/greenlight-server/greenlight-api/node_modules/swagger-tools/lib/validators.js:44:16)
  at Object.module.exports.convertValue (/Users/blakebyrnes/Projects/greenlight-server/greenlight-api/node_modules/swagger-tools/middleware/helpers.js:293:59)

```

               {
                    "in": "formData",
                    "name": "dob",
                    "description": "The user's date of birth",
                    "required": false,
                    "type": "string",
                    "format": "date"
                },
```

**Comment by blakebyrnes** [comment]
Nevermind.  Test scenario only, I think.  Was passing in null, which shouldn't happen in http requests.
